# Generated by Django 3.1.7 on 2021-03-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nov.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architect', '0001_initial'),
        ('category', '0001_initial'),
        ('client', '0001_initial'),
        ('opc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nv_Table_Comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_booking', models.CharField(default=nov.models.nv_id_generator, editable=False, max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=255, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('validite', models.CharField(choices=[('en cours', 'en cours'), ('envoyeé', 'envoyeé'), ('validé', 'validé'), ('Annuler', 'Annuler')], max_length=20)),
                ('archive', models.BooleanField(default=False)),
                ('OPC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc.opc')),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architect.architect')),
                ('category', models.ManyToManyField(blank=True, to='category.Category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_nov', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nv_Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('file_comment', models.FileField(blank=True, null=True, upload_to='')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nv_observations_creatore', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nv_observations_project', to='nov.nv_table_comercial')),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
    ]
